### ISSUE TITLE
assertion on return value of expression-bodied arrow function

### ISSUE THREAD

**Issue by m59peacemaker** [getstay/gfmjs#1]
I tried this, thinking it would work:

```js
values.map(value => typeof value /* => 'string' */)
```
I'm not sure it should work. It probably doesn't work because, with it being a return, it is different from other expressions. I'm open to the possibility this should work, but only if the solution and generated code are very obvious and definitely won't have any caveats to think about.

**Comment by TehShrike** [comment]
I think I'd *like* it to work – in my head, it would only require changing your `assertEquality(a, b)` function to return `a`?

**Comment by m59peacemaker** [comment]
Clever! And quite likely so.
